name: pokedex
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^2.1.0
  percent_indicator: ^2.1.3
  url_launcher: ^5.4.5
  esys_flutter_share: ^1.0.2
  launch_review: ^2.0.0
  image_gallery_saver: ^1.5.0
  dio: ^3.0.10
  fluttertoast: ^7.0.2
  permission_handler: ^5.0.1+1
  draggable_scrollbar: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/types/
    - .env
    - assets/data/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
